#sudo: required
#services:
#  - docker
#language: python
#python:
#  - "3.8"
## command to install dependencies
#install:
#  - pip install -r backend/requirements.txt
## command to run tests
##script:
##  - python -m pytest -v
#after_success:
#  - sh .travis/deploy_dockerhub.sh
#  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh

# config for (Django + Postgres) -> Docker -> Travis -> Heroku

language: python
python:
    - 3.6
services:
    - docker

install:
    - pip install -r backend/requirements.txt

script:
    - docker-compose -f docker-compose-prod.yml run backend python manage.py

deploy:
    provider: script
    script: bash docker_push.sh
    skip_cleanup: true
    on:
        branch: master
