version: '3.3'

volumes:
    postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
    command: /gunicorn.sh
    entrypoint: /entrypoint.sh
    ports:
      - "8000:80"
#    restart: on-failure
    env_file: .env

  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
